import { type LucideIcon } from "lucide-react";

import {
  Menu,
  X,
  ChevronDown,
  FileText,
  ShoppingBag,
  ExternalLink,
  Sprout,
  ShieldCheck,
  Tags,
  Award,
  Trash2,
  Layers2,
  Leaf,
  Plus,
  MoreVertical,
  Pencil,
  Loader2,
  Eye,
  Phone,
  UserRound,
  LogOut,
  ChevronLeft,
  UploadCloud,
  Check,
  Sigma,
  Minus,
  CheckCircle,
  Info,
} from "lucide-react";

export type TIcon = LucideIcon;

export const Icons = {
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  fileText: FileText,
  quotationCart: ShoppingBag,
  externalLink: ExternalLink,
  plant: Sprout,
  shieldCheck: ShieldCheck,
  priceTag: Tags,
  deal: Award,
  trash: Trash2,
  layer: Layers2,
  leaf: Leaf,
  plus: Plus,
  moreVertical: MoreVertical,
  edit: Pencil,
  spinner: Loader2,
  view: Eye,
  call: Phone,
  user: UserRound,
  logout: LogOut,
  chevronLeft: ChevronLeft,
  uploadCloud: UploadCloud,
  check: Check,
  sigma: Sigma,
  minus: Minus,
  checkCircle: CheckCircle,
  info: Info,
  
};
